project:
  type: website

website:
  title: "Carlotta Gherardi"
  navbar:
    # Left side of navbar
    right:
      - text: "About Me"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css

